name:                fisheye-haskell
version:             0.1.0.0
github:              "lipoyang/fisheye_examples"
license:             BSD-3-Clause
author:              "Bizan Nishimura"
maintainer:          "lipoyang"
copyright:           "2024 Bizan Nishimura"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lipoyang/fisheye_examples>

dependencies:
- base >= 4.7 && < 5
- gloss
- bytestring
- vector
- JuicyPixels

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  fisheye-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fisheye-haskell

tests:
  fisheye-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fisheye-haskell
